### ISSUE TITLE
docs updates

### ISSUE THREAD

**Issue by aladdin-add** [weiran-zsd/eslint-plugin-node#2]
- [x] 1. rename `eslint-plugin-node` => `eslint-plugin-n` in readme.
- [x] 2. replace `node/foo` => `n/foo` in readme & rule docs
- [x] 3. update rule.meta.url
- [x] 4. update scripts/*

**Comment by mcfedr** [comment]
related, the rules themselves have links to `https://github.com/mysticatea/eslint-plugin-node/blob/HEAD/docs/rules/...` - e.g. https://github.com/weiran-zsd/eslint-plugin-node/blob/master/lib/rules/callback-return.js#L15

**Comment by aladdin-add** [comment]
should have been addressed now.
