### ISSUE TITLE
n/no-unsupported-features/es-syntax with TypeScript transpilation

### ISSUE THREAD

**Issue by AndrewMSHowe** [weiran-zsd/eslint-plugin-node#27]
I'm not sure if this is a problem with eslint-plugin-n or what, but here goes...
So XO from 0.49 to 0.50 has changed from eslint-plugin-node to eslint-plugin-n, and now I am getting a bunch of errors. They're bogus because TypeScript is transpiling, so for example optional chainings & nullish coalescing operators work just fine with node 12 and don't need node 14.
The doc says "If you are using transpilers, maybe you want to ignore the warnings about some features." so I added this to my config file (which is .xo-config.json in this case, it should be forwarded to eslint):
`
		"n/no-unsupported-features/es-syntax": ["error", {
			"ignores": [
				"optionalChaining", "nullishCoalescingOperator"
			]
		}]
`
But I am still seeing the errors.
Again, I am not sure this is a problem with eslint-plugin-n or XO or what?
In future maybe it would be possible to fix things such that TypeScript transpilation would be recognised and these errors would not be generated?

**Comment by AndrewMSHowe** [comment]
More info: I downgraded XO back to 0.49, and I got a bunch of errors about "Definition for rule n/no-unsupported-features/es-syntax was not found." That was what I added to my config file. And removing that made it the errors go away. So It is somehow hooking up with eslint-plugin-n, but the ignores thing is not working I think?

**Comment by aladdin-add** [comment]
as seen in the node.green:
*optional chaining was supported in node.js>=14.5.0 https://node.green/#ES2020-features-optional-chaining-operator-----
* logical assignment: node.js>=15.14.0 https://node.green/#ES2021-features-Logical-Assignment

ofc, you can safely disable the rule if using a transpiier like ts/babel/esbuild/...

**Comment by aladdin-add** [comment]
if using xo v0.49 => the rule is `node/no-unsupported-features/es-syntax`.
xo v0.50 => `n/no-unsupported-features/es-syntax`. (a breaking change)

**Comment by AndrewMSHowe** [comment]
OK, but I had xo 0.50, and I had "n/", and it didn't seem to ignore those rules.

**Comment by AndrewMSHowe** [comment]
In theory, should this have worked? Or is there an issue with what I have written?
`"n/no-unsupported-features/es-syntax": ["error", { "ignores": [ "optionalChaining", "nullishCoalescingOperator" ] }]`

**Comment by aladdin-add** [comment]
yes,sounds a bug to me. will take a look later.~

**Comment by AndrewMSHowe** [comment]
I'm not sure where I got those strings from, but anyway changing it to "nullishCoalascingOperators" didn't fix anything. And it doesn't explain why "optionalChaining" doesn't work. Well, it does seem that maybe xo is not forwarding these or returning the above error. Someone on the eslint discord channel was sure it was a problem with the n module, but I was not so sure. I guess I'll try reporting it to xo and see if they want to punt it somewhere else :) Thanks for looking into it, anyway.
