### ISSUE TITLE
Support for "import attributes" and "import assertions"

### ISSUE THREAD

**Issue by scagood** [weiran-zsd/eslint-plugin-node#284]
I cant remember if I added this during the no unsupported PRs, but I want to keep track of the this!

`18.20, 20.10, 21.0` - experimental import attributes. (`import ? from '?' with { type: ? }`)
`17.1, 16.14` - experimental import assertions. (`import ? from '?' assert { type: ? }`)

**Comment by aladdin-add** [comment]
technically it's not possible (at least for built-in parser): eslint does not support stage<4 features, so it will just report an syntax error.

https://github.com/eslint/eslint?tab=readme-ov-file#what-about-experimental-features

**Comment by scagood** [comment]
Ah, good to know! I will leave this here to track until we can do something :)
