### ISSUE TITLE
Shared settings still called `node`

### ISSUE THREAD

**Issue by mcfedr** [weiran-zsd/eslint-plugin-node#3]
For example the `convertPath` settings, should still come under `settings.node` rather than `settings.n`

e.g. used by [shebang](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/shebang.md#shared-settings)

**Comment by aladdin-add** [comment]
The ruleId must be changed as eslint requires -while `settings` does not have to. I would like it to accept `settings/node` and `settings/n`.

**Comment by mcfedr** [comment]
Awesome, I was also thinking makes sense to accept both
